import Link from 'next/link';
import React, { useContext, useEffect } from 'react';
import { Cart } from '../../Store/CartItems';
import Head from 'next/head';

const index = () => {
    const { MyItems } = useContext(Cart);
    let prices = [];
    useEffect(() => {
        if (MyItems.length > 0) {
            for (let i = 0; i < MyItems.length - 1; i++) {
                prices.push(MyItems[i].price)
            }
        }
    });
    return (
        <>
            <Head>
                <title>Amazon/Cart</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='container-fluid'>
                <div className='container'>
                    {(MyItems.length > 0) ?
                        <div className="row my-5">
                            <div className="col-8">
                                <table className="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>Product</th>
                                            <th>Quantity</th>
                                            <th className="text-center">Price</th>
                                            <th className="text-center">Total</th>
                                            <th> </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {MyItems.map((item, index) => {
                                            return (
                                                <tr key={item.id}>
                                                    <td className="col-sm-8 col-md-6">
                                                        <div className="media d-flex justify-content-start align-items-center">
                                                            <Link className="thumbnail pull-left mx-3" href={`/products/${item.id}`}> <img className="media-object" src={item.thumbnail ? item.thumbnail : '/blankimg.png'} style={{ width: "72px", height: "72px" }} /> </Link>
                                                            <div className="media-body">
                                                                <h5 className="media-heading"><Link className='text-decoration-none text-dark' href={`/products/${item.id}`}>{item.title}</Link></h5>
                                                                <h5 className="media-heading"> by <Link className='text-decoration-none text-dark' href={`/products/${item.id}`}>{item.brand}</Link></h5>
                                                                <span>Status: </span><span className="text-success"><strong>In Stock</strong></span>
                                                            </div>
                                                        </div></td>
                                                    <td className="col-sm-1 col-md-1" style={{ textAlign: "center" }}>
                                                        <span>{item.qty}</span>
                                                    </td>
                                                    <td className="col-sm-1 col-md-1 text-center"><strong>${item.price}</strong></td>
                                                    <td className="col-sm-1 col-md-1 text-center"><strong>${item.qty * item.price}</strong></td>
                                                    <td className="col-sm-1 col-md-1">
                                                        <button type="button" className="btn btn-danger">
                                                            <span className="glyphicon glyphicon-remove"></span> Remove
                                                        </button></td>
                                                </tr>
                                            )
                                        })}
                                    </tbody>
                                </table>
                            </div>
                            <div className='col-4 justify-content-end border-start' >
                                <table>
                                    <tbody>
                                        <tr>
                                            <td>   </td>
                                            <td>   </td>
                                            <td>   </td>
                                            <td><h5>Subtotal</h5></td>
                                            <td className="text-right"><h5><strong>$24.59</strong></h5></td>
                                        </tr>
                                        <tr>
                                            <td>   </td>
                                            <td>   </td>
                                            <td>   </td>
                                            <td><h3>Total</h3></td>
                                            <td className="text-right"><h3><strong>$31.53</strong></h3></td>
                                        </tr>
                                        <tr>
                                            <td>   </td>
                                            <td>   </td>
                                            <td>   </td>
                                            {(MyItems.length > 0) ? <>
                                                <td>
                                                    <div >
                                                        <Link className="btn btn-default" href='/'>Continue Shopping</Link>
                                                    </div>
                                                </td>
                                                <td>
                                                    <button type="button" className="btn btn-success">
                                                        Checkout <span className="glyphicon glyphicon-play"></span>
                                                    </button>
                                                </td>
                                            </> :
                                                <td>
                                                    <div >
                                                        <Link className="btn btn-default" href='/'>Continue Shopping</Link>
                                                    </div>
                                                </td>
                                            }
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        :
                        <>
                            <div className='row'>
                                <div className='col-5 mx-auto p-2  text-center'>
                                    <div className='empty-image-div'>
                                        <img className='empty-img' src='/empty.png' />
                                    </div>
                                    <h4>Cart is Empty!</h4>
                                    <p>We are an award-winning creative agency, dedicated to the best result in web design, promotion, business consulting, and marketing.</p>
                                    <Link href='/' className='btn btn-dark'>Add Items</Link>
                                </div>
                            </div><br />
                        </>
                    }
                </div>
            </div>
        </>
    )
}

export default index
