import Head from 'next/head';
import Carusel from '../Components/Carusel';
import Slidebar from '../Components/Slidebar';
import Products from './products';

export default function Home() {
  return (
    <>
      <Head>
        <title>Amazon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Carusel />
      <Slidebar /><br />
      <Products />
    </>
  )
}